version: "3.1"
services:
  docker-socket-proxy:
    image: sjawhar/docker-socket-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "2376:2376"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    secrets:
      - source: ca_cert
        target: ca.pem
        mode: 0444
      - source: server_cert
        target: server-cert.pem
        mode: 0444
      - source: server_key
        target: server-key.pem
        mode: 0400

secrets:
  ca_cert:
    external: true
  server_cert:
    external: true
  server_key:
    external: true
